# Centralized Pipeline Configuration
# Use this file to manage environment variables across all workflows.

env:
  JDK_VERSION: 17
  NODE_VERSION: 20
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"
  BUILD_TOOLS_VERSION: "34.0.0"
  APP_NAME: "HowMuch"
  PACKAGE_NAME: "br.com.brunocarvalhs.howmuch"
  
  # Project Specific Paths
  MAIN_GRADLE_FILE: "app/build.gradle.kts"
  CHANGELOG_FILE: "CHANGELOG.md"
  
  # Paths
  ANDROID_LOCAL_PROPERTIES: "local.properties"
  APK_DEBUG_PATH: "app/build/outputs/apk/debug/*.apk"
  APK_RELEASE_PATH: "app/build/outputs/apk/release/*.apk"
  AAB_RELEASE_PATH: "app/build/outputs/bundle/release/*.aab"
