# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# --- Crashlytics & Debugging ---
# Preserve line numbers and source file names for stack traces
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# --- KotlinX Serialization ---
# Keep serializable classes and their companion objects/serializers
-keepattributes RuntimeVisibleAnnotations, AnnotationDefault

-keepclassmembers class * {
    @kotlinx.serialization.Serializable *;
}

-keepclassmembers class * {
    @kotlinx.serialization.SerialName *;
}

# Keep companion objects that are used for serialization
-keepclassmembers class * {
    public static ** Companion;
}

# Keep the $serializer classes generated by the plugin
-keep class *$$serializer { *; }

# --- Navigation 3 & Routes ---
# Ensure routes used in navigation are not stripped or renamed improperly
-keep @kotlinx.serialization.Serializable class *

# --- Hilt / Dagger ---
# Hilt usually bundles its own rules, but common overrides include:
-keep class dagger.hilt.android.internal.managers.** { *; }

# --- Retrofit / Moshi ---
# Retrofit 2.9.0+ has bundled rules, but if using custom adapters:
-keepclassmembers class * {
    @com.squareup.moshi.Json *;
}

# --- Firebase ---
# -keep class com.google.firebase.** { *; }

# --- Ktor / Generative AI SDK ---
-dontwarn io.ktor.**
-keep class io.ktor.** { *; }
-keep class io.ktor.client.plugins.contentnegotiation.** { *; }
-keep class io.ktor.serialization.kotlinx.json.** { *; }
-keep interface io.ktor.client.plugins.contentnegotiation.** { *; }
-keepattributes Signature, InnerClasses, EnclosingMethod


# --- Timber (Optimization: Remove logs in release) ---
-assumenosideeffects class timber.log.Timber {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
}

# Rules for core:ai moved to consumer-rules.pro
