name: Regressivo Android

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop
      - master

env:
  # Configurações Gerais
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 17
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"

  # Android
  BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_LOCAL_PROPERTIES: local.properties

  # Projeto
  APP_NAME: "HowMuch"

  # 🔑 Secrets (configurados no repo)
  GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}

jobs:
  regressivo:
    runs-on: ubuntu-24.04
    name: Regressivo
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > ${{ env.ANDROID_LOCAL_PROPERTIES }}

      - name: Create google-services.json
        run: |
          echo ${{ env.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Build APK Debug
        run: ./gradlew assembleDebug

      - name: Start Android Emulator and Run Maestro
        id: maestro_run
        continue-on-error: true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_4
          emulator-boot-timeout: 600
          disable-animations: true
          script: |
            # Instalar Maestro
            curl -Ls "https://get.maestro.mobile.dev" | bash
            echo "$HOME/.maestro/bin" >> $GITHUB_PATH
            export PATH="$PATH:$HOME/.maestro/bin"

            # Executar teste
            maestro test .maestro/test_suite.yaml --format junit --output .maestro/results
            echo "MAESTRO_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Check Maestro result
        if: always()
        run: |
          if [ "$MAESTRO_EXIT_CODE" != "0" ]; then
            echo "❌ Maestro test failed"
            exit 1
          else
            echo "✅ Maestro tests passed"
          fi

      - name: Upload Maestro Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report
          path: .maestro/results
