name: Build and Release Application

on:
  push:
    branches: [ master ]

env:
  # Configurações Gerais
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  JDK_VERSION: 17
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3072m"

  # Android
  BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_LOCAL_PROPERTIES: local.properties

  # Projeto (cada repo sobrescreve aqui)
  APP_NAME: "HowMuch"
  PACKAGE_NAME: "br.com.brunocarvalhs.howmuch"

  # Caminhos
  APK_DEBUG_PATH: app/build/outputs/apk/debug/*.apk
  APK_RELEASE_PATH: app/build/outputs/apk/release/*.apk
  AAB_RELEASE_PATH: app/build/outputs/bundle/release/*.aab

  # 🔑 Secrets (todos centralizados)
  GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  DEPLOY_SERVICE_ACCOUNT_JSON: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_JSON }}

jobs:
  checkout-and-setup:
    runs-on: ubuntu-24.04
    name: Checkout and Setup Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ env.ANDROID_HOME }}" > ${{ env.ANDROID_LOCAL_PROPERTIES }}

      - name: Create google-services.json
        run: |
          echo ${{ env.GOOGLE_SERVICE_JSON }} | base64 --decode > app/google-services.json

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload Workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: ./

  unit-tests:
    runs-on: ubuntu-24.04
    name: Unit Tests
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebug

  lint-check:
    runs-on: ubuntu-24.04
    name: Lint Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

  detekt-check:
    runs-on: ubuntu-24.04
    name: Run Detekt Check
    needs: checkout-and-setup
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt
        env:
          GRADLE_OPTS: ${{ env.GRADLE_OPTS }}

  build:
    runs-on: ubuntu-24.04
    name: Build
    needs: [unit-tests, lint-check, detekt-check]
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Give execution permissions to gradlew
        run: chmod +x gradlew

      - name: Check if keystore exists
        run: |
          if [ -f "app/release.keystore" ]; then
            echo "Keystore exists"
          else
            echo "::error::Keystore file 'app/release.keystore' does not exist. Please ensure it is in the correct location."
            exit 1
          fi

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-aab
          path: app/build/outputs/bundle/release/*.aab

  release:
    runs-on: ubuntu-24.04
    name: Create and Upload Release
    needs: [build]
    steps:
      - name: Download Workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
        continue-on-error: true

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run versioning script
        id: versioning
        run: |
          chmod +x .github/scripts/version.sh
          new_version=$(.github/scripts/version.sh)
          echo "::set-output name=new_version::$new_version"

      - name: Commit and push changes
        run: |
          # Verifica se o script de versionamento produziu uma nova versão
          if [ -n "${{ steps.versioning.outputs.new_version }}" ]; then
            git add app/build.gradle.kts CHANGELOG.md
            git commit -m "chore(release): Prepare release ${{ steps.versioning.outputs.new_version }}"
            git push
          else
            echo "Nenhuma nova versão para commitar."
          fi

      - name: Get App Version from build.gradle.kts
        run: |
          VERSION=$(grep versionName app/build.gradle.kts | sed 's/.*versionName = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_ENV
        continue-on-error: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: v${{ env.version }}
          draft: false
          prerelease: false
        continue-on-error: true

  deploy:
    runs-on: ubuntu-24.04
    name: Deploy to Google Play
    needs: release
    steps:
      - name: Download AAB Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-aab
          path: app/build/outputs/bundle/release/

      - name: Upload to Google Play (Production)
        id: deploy_prod
        continue-on-error: true
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_RELEASE_PATH }}
          track: production
          status: inProgress
          userFraction: 0.5

      - name: Upload to Google Play (Beta)
        if: steps.deploy_prod.outcome == 'failure'
        id: deploy_beta
        continue-on-error: true
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_RELEASE_PATH }}
          track: beta
          status: completed
          changesNotSentForReview: true

      - name: Upload to Google Play (Internal)
        if: steps.deploy_beta.outcome == 'failure'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: ${{ env.AAB_RELEASE_PATH }}
          track: internal
          status: completed
          changesNotSentForReview: true
